### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by voces** [voces/basic-pragma#1]
- [x] useState
- [x] useReducer
- [x] useMemo
- [x] useCallback
- [x] useRef
- [x] useContext
- [x] useEffect
- [ ] useLayoutEffect
- [x] useErrorBoundary

**Comment by RedLove** [comment]
Does `useContext/useLayoutEffect/useErrorBoundary` done? 
It help me a lot, but havn't `useContext/useLayoutEffect/useErrorBoundary` hooks.

**Comment by voces** [comment]
@RedLove I've recently picked this project back up and have implemented all hooks as of 4.4.0 except `useLayoutEffect`.

I'm curious about your use case for `useLayoutEffect`. basic-pragma is a bit more simplified than React/Preact in how `useEffect` is implemented, with the callback being invoked synchronously in the render function. `useLayoutEffect` is traditionally invoked between DOM attribute changes and screen paints, but those steps are combined in basic-pragma as the adapter's `createFrame`/`updateFrameProperties` callbacks.

**Comment by DacianSky** [comment]
I implemented the same functionality using another approach, but your solution looks much simpler, more elegant, and better.

**Comment by RedLove** [comment]
I implemented the same functionality using another approach, but your solution looks much simpler, more elegant, and better.
