### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by voces** [voces/basic-pragma#3]
A new property, `style`, is going to be added to all components. This will be an attempt at mimicking HTML style. To that end, it'll:
1) Have a generic type, equal to that of the components props, omitting style itself.
2) Recursively pass itself down, though allowing overrides at every component.
3) Act as props, but be overridden by actual props.

E.g., for the following JSX:
```tsx
const App = () => (
	<frame name="a" style={{ foo: 1, bar: 2, baz: 3 }} foo={1.1}>
		<frame name="b" style={{ bar: 2.2 }}>
			<frame name="c" baz={3.3} />
		</frame>
	</frame>
);
```
The final props received would be:
```ts
// a
{foo: 1.1, bar: 2, baz: 3, style: {foo: 1, bar: 2, baz: 3}}

// b
{foo: 1, bar: 2.2, baz: 3, style: {foo: 1, bar: 2.2, baz: 3}}

// c
{foo: 1, bar: 2.2, baz: 3.3, style: {foo: 1, bar: 2.2, baz: 3}}
```

**Comment by voces** [comment]
After recent extensive use, I no longer see a need for this.

**Comment by RedLove** [comment]
This is indeed very useful. I added a "style” property and used a flex layout engine(like yoga)to adapt the cross-platform view layer layout. But my code is too ugly.
